package org.lemonPig.os.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonPig.os.core.pojo.PermissionPOJO;
import org.lemonPig.os.core.pojo.PermissionPOJOExample;

public interface PermissionPOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int countByExample(PermissionPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int deleteByExample(PermissionPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int insert(PermissionPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int insertSelective(PermissionPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    List<PermissionPOJO> selectByExample(PermissionPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    PermissionPOJO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") PermissionPOJO record, @Param("example") PermissionPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int updateByExample(@Param("record") PermissionPOJO record, @Param("example") PermissionPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(PermissionPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PERMISSION
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int updateByPrimaryKey(PermissionPOJO record);
}