package org.lemonPig.os.core.mapper;

import org.apache.ibatis.annotations.Param;
import org.lemonPig.os.core.pojo.RoleResourcePOJO;
import org.lemonPig.os.core.pojo.RoleResourcePOJOExample;

public interface RoleResourcePOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int countByExample(RoleResourcePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int deleteByExample(RoleResourcePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int insert(RoleResourcePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int insertSelective(RoleResourcePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    RoleResourcePOJO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") RoleResourcePOJO record, @Param("example") RoleResourcePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByExample(@Param("record") RoleResourcePOJO record, @Param("example") RoleResourcePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(RoleResourcePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByPrimaryKey(RoleResourcePOJO record);
}