package org.lemonPig.os.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonPig.os.core.pojo.RolePOJO;
import org.lemonPig.os.core.pojo.RolePOJOExample;

public interface RolePOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int countByExample(RolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int deleteByExample(RolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int insert(RolePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int insertSelective(RolePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    List<RolePOJO> selectByExample(RolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    RolePOJO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") RolePOJO record, @Param("example") RolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int updateByExample(@Param("record") RolePOJO record, @Param("example") RolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(RolePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    int updateByPrimaryKey(RolePOJO record);
}