package org.lemonPig.os.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonPig.os.core.pojo.UserPOJO;
import org.lemonPig.os.core.pojo.UserPOJOExample;

public interface UserPOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int countByExample(UserPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int deleteByExample(UserPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int insert(UserPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int insertSelective(UserPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    List<UserPOJO> selectByExample(UserPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    UserPOJO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") UserPOJO record, @Param("example") UserPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByExample(@Param("record") UserPOJO record, @Param("example") UserPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(UserPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByPrimaryKey(UserPOJO record);
}