package org.lemonPig.os.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonPig.os.core.pojo.UserRolePOJO;
import org.lemonPig.os.core.pojo.UserRolePOJOExample;

public interface UserRolePOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int countByExample(UserRolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int deleteByExample(UserRolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int insert(UserRolePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int insertSelective(UserRolePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    List<UserRolePOJO> selectByExample(UserRolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    UserRolePOJO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") UserRolePOJO record, @Param("example") UserRolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByExample(@Param("record") UserRolePOJO record, @Param("example") UserRolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(UserRolePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByPrimaryKey(UserRolePOJO record);
}