package org.lemonPig.os.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonPig.os.core.pojo.UserPermissionPOJO;
import org.lemonPig.os.core.pojo.UserPermissionPOJOExample;

public interface UserPermissionPOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PERMISSION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int countByExample(UserPermissionPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PERMISSION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int deleteByExample(UserPermissionPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PERMISSION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int insert(UserPermissionPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PERMISSION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int insertSelective(UserPermissionPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PERMISSION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    List<UserPermissionPOJO> selectByExample(UserPermissionPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PERMISSION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") UserPermissionPOJO record, @Param("example") UserPermissionPOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_PERMISSION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int updateByExample(@Param("record") UserPermissionPOJO record, @Param("example") UserPermissionPOJOExample example);
}