package org.lemonPig.os.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonPig.os.core.pojo.UserRolePOJO;
import org.lemonPig.os.core.pojo.UserRolePOJOExample;

public interface UserRolePOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int countByExample(UserRolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int deleteByExample(UserRolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int insert(UserRolePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int insertSelective(UserRolePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    List<UserRolePOJO> selectByExample(UserRolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") UserRolePOJO record, @Param("example") UserRolePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    int updateByExample(@Param("record") UserRolePOJO record, @Param("example") UserRolePOJOExample example);
}