package org.lemonPig.os.core.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.lemonPig.os.core.pojo.UserResourcePOJO;
import org.lemonPig.os.core.pojo.UserResourcePOJOExample;

public interface UserResourcePOJOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int countByExample(UserResourcePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int deleteByExample(UserResourcePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int insert(UserResourcePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int insertSelective(UserResourcePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    List<UserResourcePOJO> selectByExample(UserResourcePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    UserResourcePOJO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") UserResourcePOJO record, @Param("example") UserResourcePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByExample(@Param("record") UserResourcePOJO record, @Param("example") UserResourcePOJOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(UserResourcePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resource
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    int updateByPrimaryKey(UserResourcePOJO record);
}