package org.lemonPig.os.core.pojo;

public class PermissionPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.CNAME
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.ENAME
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.RESOURCE_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Integer resourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.DESCRIPTION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.ID
     *
     * @return the value of PERMISSION.ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.ID
     *
     * @param id the value for PERMISSION.ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.CNAME
     *
     * @return the value of PERMISSION.CNAME
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.CNAME
     *
     * @param cname the value for PERMISSION.CNAME
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.ENAME
     *
     * @return the value of PERMISSION.ENAME
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.ENAME
     *
     * @param ename the value for PERMISSION.ENAME
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.RESOURCE_ID
     *
     * @return the value of PERMISSION.RESOURCE_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.RESOURCE_ID
     *
     * @param resourceId the value for PERMISSION.RESOURCE_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.DESCRIPTION
     *
     * @return the value of PERMISSION.DESCRIPTION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.DESCRIPTION
     *
     * @param description the value for PERMISSION.DESCRIPTION
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}