package org.lemonPig.os.core.pojo;

public class ResourcePOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.SECURITY_LEVEL
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Integer securityLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.REQUEST_MAPPING_INFO
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private String requestMappingInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RESOURCE.HANDLERMETHOD
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private String handlermethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.ID
     *
     * @return the value of RESOURCE.ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.ID
     *
     * @param id the value for RESOURCE.ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.SECURITY_LEVEL
     *
     * @return the value of RESOURCE.SECURITY_LEVEL
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Integer getSecurityLevel() {
        return securityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.SECURITY_LEVEL
     *
     * @param securityLevel the value for RESOURCE.SECURITY_LEVEL
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setSecurityLevel(Integer securityLevel) {
        this.securityLevel = securityLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.REQUEST_MAPPING_INFO
     *
     * @return the value of RESOURCE.REQUEST_MAPPING_INFO
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public String getRequestMappingInfo() {
        return requestMappingInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.REQUEST_MAPPING_INFO
     *
     * @param requestMappingInfo the value for RESOURCE.REQUEST_MAPPING_INFO
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setRequestMappingInfo(String requestMappingInfo) {
        this.requestMappingInfo = requestMappingInfo == null ? null : requestMappingInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RESOURCE.HANDLERMETHOD
     *
     * @return the value of RESOURCE.HANDLERMETHOD
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public String getHandlermethod() {
        return handlermethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RESOURCE.HANDLERMETHOD
     *
     * @param handlermethod the value for RESOURCE.HANDLERMETHOD
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setHandlermethod(String handlermethod) {
        this.handlermethod = handlermethod == null ? null : handlermethod.trim();
    }
}