package org.lemonPig.os.core.pojo;

public class ResourcePOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.cname
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.ename
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.permission
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private String permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.grantAble
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private Byte grantAble;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.cname
     *
     * @return the value of resource.cname
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.cname
     *
     * @param cname the value for resource.cname
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.ename
     *
     * @return the value of resource.ename
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.ename
     *
     * @param ename the value for resource.ename
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.permission
     *
     * @return the value of resource.permission
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.permission
     *
     * @param permission the value for resource.permission
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.grantAble
     *
     * @return the value of resource.grantAble
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public Byte getGrantAble() {
        return grantAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.grantAble
     *
     * @param grantAble the value for resource.grantAble
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setGrantAble(Byte grantAble) {
        this.grantAble = grantAble;
    }
}