package org.lemonPig.os.core.pojo;

import java.util.ArrayList;
import java.util.List;

public class ResourcePOJOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public ResourcePOJOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelIsNull() {
            addCriterion("SECURITY_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelIsNotNull() {
            addCriterion("SECURITY_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelEqualTo(Integer value) {
            addCriterion("SECURITY_LEVEL =", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelNotEqualTo(Integer value) {
            addCriterion("SECURITY_LEVEL <>", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelGreaterThan(Integer value) {
            addCriterion("SECURITY_LEVEL >", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("SECURITY_LEVEL >=", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelLessThan(Integer value) {
            addCriterion("SECURITY_LEVEL <", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelLessThanOrEqualTo(Integer value) {
            addCriterion("SECURITY_LEVEL <=", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelIn(List<Integer> values) {
            addCriterion("SECURITY_LEVEL in", values, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelNotIn(List<Integer> values) {
            addCriterion("SECURITY_LEVEL not in", values, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelBetween(Integer value1, Integer value2) {
            addCriterion("SECURITY_LEVEL between", value1, value2, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("SECURITY_LEVEL not between", value1, value2, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoIsNull() {
            addCriterion("REQUEST_MAPPING_INFO is null");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoIsNotNull() {
            addCriterion("REQUEST_MAPPING_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoEqualTo(String value) {
            addCriterion("REQUEST_MAPPING_INFO =", value, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoNotEqualTo(String value) {
            addCriterion("REQUEST_MAPPING_INFO <>", value, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoGreaterThan(String value) {
            addCriterion("REQUEST_MAPPING_INFO >", value, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoGreaterThanOrEqualTo(String value) {
            addCriterion("REQUEST_MAPPING_INFO >=", value, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoLessThan(String value) {
            addCriterion("REQUEST_MAPPING_INFO <", value, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoLessThanOrEqualTo(String value) {
            addCriterion("REQUEST_MAPPING_INFO <=", value, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoLike(String value) {
            addCriterion("REQUEST_MAPPING_INFO like", value, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoNotLike(String value) {
            addCriterion("REQUEST_MAPPING_INFO not like", value, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoIn(List<String> values) {
            addCriterion("REQUEST_MAPPING_INFO in", values, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoNotIn(List<String> values) {
            addCriterion("REQUEST_MAPPING_INFO not in", values, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoBetween(String value1, String value2) {
            addCriterion("REQUEST_MAPPING_INFO between", value1, value2, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andRequestMappingInfoNotBetween(String value1, String value2) {
            addCriterion("REQUEST_MAPPING_INFO not between", value1, value2, "requestMappingInfo");
            return (Criteria) this;
        }

        public Criteria andHandlermethodIsNull() {
            addCriterion("HANDLERMETHOD is null");
            return (Criteria) this;
        }

        public Criteria andHandlermethodIsNotNull() {
            addCriterion("HANDLERMETHOD is not null");
            return (Criteria) this;
        }

        public Criteria andHandlermethodEqualTo(String value) {
            addCriterion("HANDLERMETHOD =", value, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodNotEqualTo(String value) {
            addCriterion("HANDLERMETHOD <>", value, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodGreaterThan(String value) {
            addCriterion("HANDLERMETHOD >", value, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodGreaterThanOrEqualTo(String value) {
            addCriterion("HANDLERMETHOD >=", value, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodLessThan(String value) {
            addCriterion("HANDLERMETHOD <", value, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodLessThanOrEqualTo(String value) {
            addCriterion("HANDLERMETHOD <=", value, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodLike(String value) {
            addCriterion("HANDLERMETHOD like", value, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodNotLike(String value) {
            addCriterion("HANDLERMETHOD not like", value, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodIn(List<String> values) {
            addCriterion("HANDLERMETHOD in", values, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodNotIn(List<String> values) {
            addCriterion("HANDLERMETHOD not in", values, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodBetween(String value1, String value2) {
            addCriterion("HANDLERMETHOD between", value1, value2, "handlermethod");
            return (Criteria) this;
        }

        public Criteria andHandlermethodNotBetween(String value1, String value2) {
            addCriterion("HANDLERMETHOD not between", value1, value2, "handlermethod");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RESOURCE
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RESOURCE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}