package org.lemonPig.os.core.pojo;

public class RolePermissionPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PERMISSION.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PERMISSION.ROLE_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PERMISSION.PERMISSION_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE_PERMISSION.GRANT_USER_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long grantUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PERMISSION.ID
     *
     * @return the value of ROLE_PERMISSION.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PERMISSION.ID
     *
     * @param id the value for ROLE_PERMISSION.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PERMISSION.ROLE_ID
     *
     * @return the value of ROLE_PERMISSION.ROLE_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PERMISSION.ROLE_ID
     *
     * @param roleId the value for ROLE_PERMISSION.ROLE_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PERMISSION.PERMISSION_ID
     *
     * @return the value of ROLE_PERMISSION.PERMISSION_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PERMISSION.PERMISSION_ID
     *
     * @param permissionId the value for ROLE_PERMISSION.PERMISSION_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE_PERMISSION.GRANT_USER_ID
     *
     * @return the value of ROLE_PERMISSION.GRANT_USER_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getGrantUserId() {
        return grantUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE_PERMISSION.GRANT_USER_ID
     *
     * @param grantUserId the value for ROLE_PERMISSION.GRANT_USER_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setGrantUserId(Long grantUserId) {
        this.grantUserId = grantUserId;
    }
}