package org.lemonPig.os.core.pojo;

public class RolePOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ENAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.CNAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.GRANTABLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Byte grantable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ID
     *
     * @return the value of ROLE.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ID
     *
     * @param id the value for ROLE.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ENAME
     *
     * @return the value of ROLE.ENAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ENAME
     *
     * @param ename the value for ROLE.ENAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.CNAME
     *
     * @return the value of ROLE.CNAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.CNAME
     *
     * @param cname the value for ROLE.CNAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.GRANTABLE
     *
     * @return the value of ROLE.GRANTABLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Byte getGrantable() {
        return grantable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.GRANTABLE
     *
     * @param grantable the value for ROLE.GRANTABLE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setGrantable(Byte grantable) {
        this.grantable = grantable;
    }
}