package org.lemonPig.os.core.pojo;

public class UserRolePOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.USER_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.ROLE_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.ID
     *
     * @return the value of USER_ROLE.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.ID
     *
     * @param id the value for USER_ROLE.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.USER_ID
     *
     * @return the value of USER_ROLE.USER_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.USER_ID
     *
     * @param userId the value for USER_ROLE.USER_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.ROLE_ID
     *
     * @return the value of USER_ROLE.ROLE_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.ROLE_ID
     *
     * @param roleId the value for USER_ROLE.ROLE_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}