package org.lemonPig.os.core.pojo;

public class UserMetadataPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.ENAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.CNAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.TEL
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.ADDRESS
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.QQ
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.AGE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.SEX
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.PHOTO
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_METADATA.USER_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.ID
     *
     * @return the value of USER_METADATA.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.ID
     *
     * @param id the value for USER_METADATA.ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.ENAME
     *
     * @return the value of USER_METADATA.ENAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.ENAME
     *
     * @param ename the value for USER_METADATA.ENAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.CNAME
     *
     * @return the value of USER_METADATA.CNAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.CNAME
     *
     * @param cname the value for USER_METADATA.CNAME
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.TEL
     *
     * @return the value of USER_METADATA.TEL
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.TEL
     *
     * @param tel the value for USER_METADATA.TEL
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.ADDRESS
     *
     * @return the value of USER_METADATA.ADDRESS
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.ADDRESS
     *
     * @param address the value for USER_METADATA.ADDRESS
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.QQ
     *
     * @return the value of USER_METADATA.QQ
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.QQ
     *
     * @param qq the value for USER_METADATA.QQ
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.AGE
     *
     * @return the value of USER_METADATA.AGE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.AGE
     *
     * @param age the value for USER_METADATA.AGE
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.SEX
     *
     * @return the value of USER_METADATA.SEX
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.SEX
     *
     * @param sex the value for USER_METADATA.SEX
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.PHOTO
     *
     * @return the value of USER_METADATA.PHOTO
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.PHOTO
     *
     * @param photo the value for USER_METADATA.PHOTO
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_METADATA.USER_ID
     *
     * @return the value of USER_METADATA.USER_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_METADATA.USER_ID
     *
     * @param userId the value for USER_METADATA.USER_ID
     *
     * @mbggenerated Sun Jun 07 15:19:11 GMT+08:00 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}