package org.lemonPig.os.core.pojo;

public class UserMetadataPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.id
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.ename
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.cname
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.tel
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.address
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.qq
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.age
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.sex
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.photo
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_metadata.user_id
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    private Long user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.id
     *
     * @return the value of user_metadata.id
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.id
     *
     * @param id the value for user_metadata.id
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.ename
     *
     * @return the value of user_metadata.ename
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.ename
     *
     * @param ename the value for user_metadata.ename
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.cname
     *
     * @return the value of user_metadata.cname
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.cname
     *
     * @param cname the value for user_metadata.cname
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.tel
     *
     * @return the value of user_metadata.tel
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.tel
     *
     * @param tel the value for user_metadata.tel
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.address
     *
     * @return the value of user_metadata.address
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.address
     *
     * @param address the value for user_metadata.address
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.qq
     *
     * @return the value of user_metadata.qq
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.qq
     *
     * @param qq the value for user_metadata.qq
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.age
     *
     * @return the value of user_metadata.age
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.age
     *
     * @param age the value for user_metadata.age
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.sex
     *
     * @return the value of user_metadata.sex
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.sex
     *
     * @param sex the value for user_metadata.sex
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.photo
     *
     * @return the value of user_metadata.photo
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.photo
     *
     * @param photo the value for user_metadata.photo
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_metadata.user_id
     *
     * @return the value of user_metadata.user_id
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_metadata.user_id
     *
     * @param user_id the value for user_metadata.user_id
     *
     * @mbggenerated Sun May 24 19:46:56 GMT+08:00 2015
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }
}