package org.lemonPig.os.core.pojo;

public class UserPermissionPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PERMISSION.USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PERMISSION.PERMISSION_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Long permissionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PERMISSION.GRANT_USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Long grantUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PERMISSION.GRANTABLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Byte grantable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PERMISSION.USER_ID
     *
     * @return the value of USER_PERMISSION.USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PERMISSION.USER_ID
     *
     * @param userId the value for USER_PERMISSION.USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PERMISSION.PERMISSION_ID
     *
     * @return the value of USER_PERMISSION.PERMISSION_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Long getPermissionId() {
        return permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PERMISSION.PERMISSION_ID
     *
     * @param permissionId the value for USER_PERMISSION.PERMISSION_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setPermissionId(Long permissionId) {
        this.permissionId = permissionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PERMISSION.GRANT_USER_ID
     *
     * @return the value of USER_PERMISSION.GRANT_USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Long getGrantUserId() {
        return grantUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PERMISSION.GRANT_USER_ID
     *
     * @param grantUserId the value for USER_PERMISSION.GRANT_USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setGrantUserId(Long grantUserId) {
        this.grantUserId = grantUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PERMISSION.GRANTABLE
     *
     * @return the value of USER_PERMISSION.GRANTABLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Byte getGrantable() {
        return grantable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PERMISSION.GRANTABLE
     *
     * @param grantable the value for USER_PERMISSION.GRANTABLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setGrantable(Byte grantable) {
        this.grantable = grantable;
    }
}