package org.lemonPig.os.core.pojo;

public class UserRolePOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.GRANTABLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Byte grantable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.GRANTED_USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    private Long grantedUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.USER_ID
     *
     * @return the value of USER_ROLE.USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.USER_ID
     *
     * @param userId the value for USER_ROLE.USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.ROLE_ID
     *
     * @return the value of USER_ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.ROLE_ID
     *
     * @param roleId the value for USER_ROLE.ROLE_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.GRANTABLE
     *
     * @return the value of USER_ROLE.GRANTABLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Byte getGrantable() {
        return grantable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.GRANTABLE
     *
     * @param grantable the value for USER_ROLE.GRANTABLE
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setGrantable(Byte grantable) {
        this.grantable = grantable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.GRANTED_USER_ID
     *
     * @return the value of USER_ROLE.GRANTED_USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public Long getGrantedUserId() {
        return grantedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.GRANTED_USER_ID
     *
     * @param grantedUserId the value for USER_ROLE.GRANTED_USER_ID
     *
     * @mbggenerated Fri Jul 10 19:11:38 GMT+08:00 2015
     */
    public void setGrantedUserId(Long grantedUserId) {
        this.grantedUserId = grantedUserId;
    }
}